apiVersion: v2
name: dns-operator-route53
version: 0.11.0
appVersion: 0.11.0
description: "Operator for managing DNS zones and records for CAPO clusters"
home: "https://github.com/giantswarm/dns-operator-route53"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: "rocket"
  config.giantswarm.io/version: 1.x.x
